### PR TITLE
Update: Detect download error and simplify the things

### PR DESCRIPTION
**Pull request by Caio99BR**

### CODE REVIEW

**Comment by muhasturk** [comment]
Have you tried real or virtual machine?

**Comment by Caio99BR** [comment]
Real, all tested

**Comment by muhasturk** [comment]
Thank you for your contribution

**Comment by Caio99BR** [comment]
:+1: I need to say thanks for you work, thanks again.

**Comment by muhasturk** [comment]
Script works well but almost no one know this script. We should spread.

**Pull request merged**
